In [6]:
import numpy as np


In [18]:
neighs_y=np.array([0,1,2])
diffs = np.insert(np.diff(neighs_y), 0, 999)
feats = np.unique(neighs_y[diffs == 0], return_counts=True)
if len(feats[0])==0:
    feats=1
else:
    feats=feats[1].max() + 1
feats

1

In [51]:
x=np.array([0,0,3,4,0])


array([2])

In [89]:
def func(x):
    x=np.array(x)
    if len(x)==1:
        return 1
    suma=np.where(x==x[0],0,1)
    return suma.cumsum()[np.argwhere(suma)[0]]

In [94]:
assert func([0])==1
assert func([0,1,1])==1
assert func([0,1,0,1])==1
assert func([1,1,2,2,1])==2

AssertionError: 

In [136]:
x=np.array([0,0,1,0,1])
suma=np.where(x==x[0],1,0)
np.equal(suma.cumsum(),np.arange(1,6)).sum()

2

In [127]:
cs

array([1, 2, 3, 3, 3])

In [119]:
np.argwhere(np.diff(cs)).ravel()

array([2])